spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trash?createdDatabaseIfNotExist=true&useUnicode=true&characterSetResults=UTF-8&useSSL=true
    username: root
    password: sjha782800!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 194536636525-hfnhvhkl3h01dtddcu8fac5te4247616.apps.googleusercontent.com
            clientSecret: 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
#            scope:
#              - email                              // (1)
#              - profile                            // (2)
# JWT
jwt:
  key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQ=
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

#spring:
#  output:
#    ansi:
#      enabled: ALWAYS
#
#      datasource:
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:test
#        username: sa
#        password:
#
#      h2:
#        console:
#          enabled: true
#          path: /h2
#      jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        hibernate:
#          ddl-auto: auto
#  config:
#    use-legacy-processing: true
#  jpa:
#    show-sql: true
#    hibernate:
#    properties:
#      hibernate:
#        format_sql: false
#        highlight_sql: false
#        color-codes: false
#        use_sql_comments: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
